apiVersion: v1
kind: Service
metadata:
  labels:
    app: python-api-sample
  name: python-api-sample-service
  namespace: default
spec:
  ports:
  - port: 5001
    protocol: TCP
    targetPort: 5001
  selector:
    app: python-api-sample
  sessionAffinity: None
  type: ClusterIP
